name: "Merge Composite Action Build and SQ Analysis"
description: "Composite Action Template For Develop branch"
inputs:  

  SONAR_HOST_URL: 
      description: "Sonar Host URL"
      required: true
      
  SONAR_TOKEN: 
      description: "Sonar Token"
      required: true
      
  BUILD_NUMBER: 
      description: "Build Number"
      required: true
      default: "${{ github.run_number }}"


runs:
  using: "composite"

  steps:

    # Setup helm
    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: ${{inputs.HELM_VERSION}}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java version
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    # Build Code
    - name: Build code & test
      run: ./gradlew clean build
      shell: bash

    #Sonarqube Analysis      
    - name: Publish to Sonar
      run: ./gradlew sonarqube
        -Dsonar.projectKey=${{env.SONAR_PROJECT_KEY}}
        -Dsonar.host.url=${{env.SONAR_HOST_URL}}
        -Dsonar.login=${{env.SONAR_LOGIN}}
      shell: bash  
